spring:
  application:
    name: project-manager
  datasource:
    url: jdbc:h2:file:./src/main/resources/cache/db
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
logging:
  level:
    org.hibernate.type.descriptor.sql.BasicBinder: trace
    pers.dog.project.manager: debug
project-manager:
  gitlab:
    home: ${PM_GITLAB_HOME}
  iam:
    admin-username: ${PM_IAM_ADMIN}