spring:
  application:
    name: project-manager
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/project_manager?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root
  liquibase:
    change-log: classpath:/db/changelog/changelog-master.xml
logging:
  level:
    pers.dog.project.manager: debug
project-manager:
  gitlab:
    home: ${PM_GITLAB_HOME}
  iam:
    admin-username: ${PM_IAM_ADMIN}